/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package presentacion;

import DAOS.TareaDAO;
import Objeto_negocio.Estado;
import Objeto_negocio.Tarea;
import java.util.ArrayList;
import javax.swing.DropMode;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lossa
 */
public class FrmMenuTareas extends javax.swing.JFrame {

    /** Creates new form FrmMenuTareas */
    
    private TareaDAO tareaDao;
    private ArrayList<Tarea> tareasPendientes;
    private ArrayList<Tarea> tareasEnProgreso;
    private ArrayList<Tarea> tareasTerminadas;
    public FrmMenuTareas() {
        initComponents();
        this.tareaDao=new TareaDAO();
        this.cargarTareasPendientes();
        this.cargarTareasEnProgreso();
        this.cargarTareasTerminadas();
        
    }

    String [] botones={"Si","No"};
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbPendiente = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbEnProgreso = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbTerminado = new javax.swing.JTable();
        btnReanudar = new javax.swing.JButton();
        Salir = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnPausar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        lblTemporizador = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbPendiente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Descripción"
            }
        ));
        tbPendiente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbPendienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbPendiente);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 190, 300));

        tbEnProgreso.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Descripción"
            }
        ));
        tbEnProgreso.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                tbEnProgresoMouseDragged(evt);
            }
        });
        tbEnProgreso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbEnProgresoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbEnProgreso);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 190, 300));

        tbTerminado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Descripción"
            }
        ));
        jScrollPane3.setViewportView(tbTerminado);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, 190, 300));

        btnReanudar.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnReanudar.setText("Reanudar");
        getContentPane().add(btnReanudar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 210, 130, 30));

        Salir.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        Salir.setText("Salir");
        getContentPane().add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 340, 130, 30));

        btnCancelar.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnCancelar.setText("Cancelar");
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 250, 130, 30));

        btnPausar.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnPausar.setText("Pausar");
        getContentPane().add(btnPausar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 170, 130, 30));

        btnAgregar.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnAgregar.setText("Agregar tarea");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 70, 130, 30));

        lblTemporizador.setFont(new java.awt.Font("SansSerif", 1, 48)); // NOI18N
        lblTemporizador.setText("00:00");
        getContentPane().add(lblTemporizador, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 110, -1, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/MenuTareas.png"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
     FrmAgregarTareas agregar=new FrmAgregarTareas();
     agregar.jFrameMenu(this);
     agregar.setVisible(true);
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void tbPendienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbPendienteMouseClicked
       try{
           int indiceFelaSeleccionada = this.tbPendiente.getSelectedRow(); 
           Tarea tarea= this.tareasPendientes.get(indiceFelaSeleccionada);
           tarea.setEstado(Estado.EN_PROGRESO);
           tareaDao.actualizar(tarea);
           this.cargarTareasPendientes();
           this.cargarTareasEnProgreso();
        }catch(Exception ex){
              JOptionPane.showMessageDialog(this, "no se pudieron obtener los datos de la tabla " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE); 
        }
    }//GEN-LAST:event_tbPendienteMouseClicked

    private void tbEnProgresoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbEnProgresoMouseClicked
        try{
           int opcion = JOptionPane.showOptionDialog(this, "Desea finalizar la tarea?", "Finalizar tarea", JOptionPane.YES_NO_CANCEL_OPTION,JOptionPane.INFORMATION_MESSAGE,null,botones,botones[0]);
           
           if(opcion==0){
               int indiceFelaSeleccionada = this.tbEnProgreso.getSelectedRow(); 
               Tarea tarea= this.tareasEnProgreso.get(indiceFelaSeleccionada);
               tarea.setEstado(Estado.TERMINADA);
               tareaDao.actualizar(tarea);
               this.cargarTareasEnProgreso();
               this.cargarTareasTerminadas();
               JOptionPane.showMessageDialog(null, "Tarea finalizada con exito", "Tarea terminada", JOptionPane.INFORMATION_MESSAGE);
          }
        }catch(Exception ex){
              JOptionPane.showMessageDialog(this, "no se pudieron obtener los datos de la tabla " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE); 
        }
    }//GEN-LAST:event_tbEnProgresoMouseClicked

    private void tbEnProgresoMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbEnProgresoMouseDragged
        tbEnProgreso.setDragEnabled(true);
    }//GEN-LAST:event_tbEnProgresoMouseDragged

    
    public void cargarTareasPendientes(){
        try{
        this.tareasPendientes=this.tareaDao.consultarEstado(Estado.PENDIENTE);
        DefaultTableModel modeloTabla=(DefaultTableModel)this.tbPendiente.getModel();
        modeloTabla.setRowCount(0);
        for (Tarea tarea : tareasPendientes) {
            Object[] filaDatos=new Object[2];
            filaDatos[0]=tarea.getNombre();
            filaDatos[1]=tarea.getDescripcion();
            modeloTabla.addRow(filaDatos);
        }
        }catch(Exception ex){
              JOptionPane.showMessageDialog(this, "no se pudieron obtener los datos de la tabla"+" "+ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE); 
        }
    }
    
    private void cargarTareasEnProgreso(){
        try{
        this.tareasEnProgreso=this.tareaDao.consultarEstado(Estado.EN_PROGRESO);
        DefaultTableModel modeloTabla=(DefaultTableModel)this.tbEnProgreso.getModel();
        modeloTabla.setRowCount(0);
        for (Tarea tarea : tareasEnProgreso) {
            Object[] filaDatos=new Object[2];
            filaDatos[0]=tarea.getNombre();
            filaDatos[1]=tarea.getDescripcion();
            modeloTabla.addRow(filaDatos);
        }
        }catch(Exception ex){
              JOptionPane.showMessageDialog(this, "no se pudieron obtener los datos de la tabla"+" "+ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE); 
        }
    }
    
    private void cargarTareasTerminadas(){
        try{    
        this.tareasTerminadas=this.tareaDao.consultarEstado(Estado.TERMINADA);
        DefaultTableModel modeloTabla=(DefaultTableModel)this.tbTerminado.getModel();
        modeloTabla.setRowCount(0);
        for (Tarea tarea : tareasTerminadas) {
            Object[] filaDatos=new Object[2];
            filaDatos[0]=tarea.getNombre();
            filaDatos[1]=tarea.getDescripcion();
            modeloTabla.addRow(filaDatos);
        }
        }catch(Exception ex){
              JOptionPane.showMessageDialog(this, "no se pudieron obtener los datos de la tabla"+" "+ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE); 
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenuTareas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenuTareas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenuTareas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenuTareas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenuTareas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Salir;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnPausar;
    private javax.swing.JButton btnReanudar;
    private javax.swing.JLabel fondo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblTemporizador;
    private javax.swing.JTable tbEnProgreso;
    private javax.swing.JTable tbPendiente;
    private javax.swing.JTable tbTerminado;
    // End of variables declaration//GEN-END:variables

}
