/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package presentacion;

import DAOS.TareaDAO;
import Objeto_negocio.Estado;
import Objeto_negocio.Tarea;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

public class FrmMenuTareas extends javax.swing.JFrame {

    /** Creates new form FrmMenuTareas */
    
    private TareaDAO tareaDao;
    private ArrayList<Tarea> tareasPendientes;
    private ArrayList<Tarea> tareasEnProgreso;
    private ArrayList<Tarea> tareasTerminadas;
    private int minutos;
    private int segundos;
    private boolean descanso;
    private boolean mensaje;
    private int numDescansos;
    private Timer timer;
    
    public FrmMenuTareas() {
        initComponents();
        setLocationRelativeTo(null);
        this.timer= new Timer(1, acciones);
        this.tareaDao=new TareaDAO();
        this.minutos=0;
        this.segundos=0;
        this.descanso=false;
        this.mensaje=false;
        this.numDescansos=0;
        this.cargarTareasPendientes();
        this.cargarTareasEnProgreso();
        this.cargarTareasTerminadas();
        if(this.tareasEnProgreso.isEmpty()) btnIniciarReanudar.setEnabled(false);
        btnPausar.setEnabled(false);
        btnCancelar.setEnabled(false);
    }
    private int opciones;
    private int auxOpcion=-1;
    private String [] botones={"Sí","No"};
    private String [] botones2={"Confirmar","Omitir"};
    private ActionListener acciones = new ActionListener(){

        @Override
        public void actionPerformed(ActionEvent ae) {
            if(segundos != 0 || minutos != 0) {
                if(segundos==1 && minutos==0 && !descanso){
                    if(auxOpcion==0){
                        descanso=true;
                    } else if(auxOpcion==1){
                        numDescansos++;
                        System.out.println(numDescansos);
                        if(numDescansos==4) numDescansos=0;
                    }
                    segundos--;
                } else if(segundos==1 && minutos==0 && descanso){
                    numDescansos++;
                    System.out.println(numDescansos);
                    if(numDescansos==4) numDescansos=0;
                    descanso=false;
                    segundos--;
                } else if(segundos!=0){
                    segundos--;
                    
                } else if(minutos!=0){
                    minutos--;
                    segundos=59;
                }
                actualizarTemporizador();
                if(segundos==5 && minutos==0){
                    if(descanso){
                        JOptionPane.showMessageDialog(null, "El tiempo de descanso está por terminar", "Tiempo de descanso finaliza pronto", JOptionPane.INFORMATION_MESSAGE);
                    }else{
                        opciones= JOptionPane.showOptionDialog(null, "El tiempo de actividades está por terminar", "Tiempo de actividades finaliza pronto", JOptionPane.YES_NO_CANCEL_OPTION,JOptionPane.INFORMATION_MESSAGE,null,botones2,botones2[0]);
                        auxOpcion= opciones;
                    }
                    mensaje= true;
                }
            }
            else if(mensaje){
                establecerTiempo();
            }
        }
        
    };
    
    private void actualizarTemporizador() {
        String tiempo = (minutos<=9?"0":"")+minutos+":"+(segundos<=9?"0":"")+segundos;
        lblTemporizador.setText(tiempo);
        lblTemporizador.repaint();
        if(numDescansos!=0){
            lblNumDescansos.setText((numDescansos)+"");
        }else{
            lblNumDescansos.setText(numDescansos+"");
        }
        lblNumDescansos.repaint();
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbPendiente = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbEnProgreso = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbTerminado = new javax.swing.JTable();
        btnIniciarReanudar = new javax.swing.JButton();
        Salir = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnPausar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        lblInformacionDescansos = new javax.swing.JLabel();
        lblNumDescansos = new javax.swing.JLabel();
        lblTemporizador = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbPendiente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Descripción"
            }
        ));
        tbPendiente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbPendienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbPendiente);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 190, 300));

        tbEnProgreso.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Descripción"
            }
        ));
        tbEnProgreso.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                tbEnProgresoMouseDragged(evt);
            }
        });
        tbEnProgreso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbEnProgresoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbEnProgreso);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 190, 300));

        tbTerminado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Descripción"
            }
        ));
        jScrollPane3.setViewportView(tbTerminado);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, 190, 300));

        btnIniciarReanudar.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnIniciarReanudar.setText("Iniciar");
        btnIniciarReanudar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarReanudarActionPerformed(evt);
            }
        });
        getContentPane().add(btnIniciarReanudar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 230, 130, 30));

        Salir.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        getContentPane().add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 350, 130, 30));

        btnCancelar.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 310, 130, 30));

        btnPausar.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnPausar.setText("Pausar");
        btnPausar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPausarActionPerformed(evt);
            }
        });
        getContentPane().add(btnPausar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 270, 130, 30));

        btnAgregar.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnAgregar.setText("Agregar tarea");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 120, 130, 30));

        lblInformacionDescansos.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lblInformacionDescansos.setText("Número de descansos");
        getContentPane().add(lblInformacionDescansos, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 60, -1, -1));

        lblNumDescansos.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        lblNumDescansos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNumDescansos.setText("0");
        getContentPane().add(lblNumDescansos, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 70, 30, -1));

        lblTemporizador.setFont(new java.awt.Font("SansSerif", 1, 48)); // NOI18N
        lblTemporizador.setText("00:00");
        getContentPane().add(lblTemporizador, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 160, -1, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/MenuTareas.png"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
     FrmAgregarTareas agregar=new FrmAgregarTareas();
     agregar.jFrameMenu(this);
     agregar.setVisible(true);
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void tbPendienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbPendienteMouseClicked
       try{
           int indiceFelaSeleccionada = this.tbPendiente.getSelectedRow(); 
           Tarea tarea= this.tareasPendientes.get(indiceFelaSeleccionada);
           tarea.setEstado(Estado.EN_PROGRESO);
           tareaDao.actualizar(tarea);
           this.cargarTareasPendientes();
           this.cargarTareasEnProgreso();
        }catch(Exception ex){
              JOptionPane.showMessageDialog(this, "No se pudieron obtener los datos de la tabla " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE); 
        }
    }//GEN-LAST:event_tbPendienteMouseClicked

    private void tbEnProgresoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbEnProgresoMouseClicked
        try{
           int opcion = JOptionPane.showOptionDialog(this, "¿Desea finalizar la tarea?", "Finalizar tarea", JOptionPane.YES_NO_CANCEL_OPTION,JOptionPane.INFORMATION_MESSAGE,null,botones,botones[0]);
           
            if(opcion==0){
                int indiceFelaSeleccionada = this.tbEnProgreso.getSelectedRow(); 
                Tarea tarea= this.tareasEnProgreso.get(indiceFelaSeleccionada);
                tarea.setEstado(Estado.TERMINADA);
                tareaDao.actualizar(tarea);
                this.cargarTareasEnProgreso();
                this.cargarTareasTerminadas();
                JOptionPane.showMessageDialog(null, "Tarea finalizada con éxito", "Tarea terminada", JOptionPane.INFORMATION_MESSAGE);
            }
        }catch(Exception ex){
              JOptionPane.showMessageDialog(this, "No se pudieron obtener los datos de la tabla " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE); 
        }
    }//GEN-LAST:event_tbEnProgresoMouseClicked

    private void tbEnProgresoMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbEnProgresoMouseDragged
        tbEnProgreso.setDragEnabled(true);
    }//GEN-LAST:event_tbEnProgresoMouseDragged

    private void btnIniciarReanudarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarReanudarActionPerformed
        empezarTemporizador();
        btnIniciarReanudar.setEnabled(false);
        btnIniciarReanudar.setText("Reanudar");
        btnPausar.setEnabled(true);
        btnCancelar.setEnabled(true);
    }//GEN-LAST:event_btnIniciarReanudarActionPerformed

    private void btnPausarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPausarActionPerformed
        timer.stop();
        JOptionPane.showMessageDialog(null, "El temporizador está en pausa", "El temporizador está en pausa", JOptionPane.INFORMATION_MESSAGE);
        btnIniciarReanudar.setEnabled(true);
        btnPausar.setEnabled(false);
    }//GEN-LAST:event_btnPausarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        int opcion = JOptionPane.showOptionDialog(this, "¿Desea restablecer el temporizador?", "Restablecer temporizador", JOptionPane.YES_NO_CANCEL_OPTION,JOptionPane.INFORMATION_MESSAGE,null,botones,botones[0]);
           
        if(opcion==0){
            if(timer.isRunning()) 
            {
                timer.stop();
                btnIniciarReanudar.setEnabled(true);
            }
            btnIniciarReanudar.setText("Iniciar");
            btnPausar.setEnabled(false);
            btnCancelar.setEnabled(false);
            minutos=0; segundos=0;
            actualizarTemporizador();
         }
        
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        if(timer.isRunning()) 
        {
            timer.stop();
        }
        this.dispose();
    }//GEN-LAST:event_SalirActionPerformed

    
    public void cargarTareasPendientes(){
        try{
            this.tareasPendientes=this.tareaDao.consultarEstado(Estado.PENDIENTE);
            DefaultTableModel modeloTabla=(DefaultTableModel)this.tbPendiente.getModel();
            modeloTabla.setRowCount(0);
            for (Tarea tarea : tareasPendientes) {
                Object[] filaDatos=new Object[2];
                filaDatos[0]=tarea.getNombre();
                filaDatos[1]=tarea.getDescripcion();
                modeloTabla.addRow(filaDatos);
        }
        }catch(Exception ex){
              JOptionPane.showMessageDialog(this, "No se pudieron obtener los datos de la tabla"+" "+ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE); 
        }
    }
    
    private void cargarTareasEnProgreso(){
        try{
            this.tareasEnProgreso=this.tareaDao.consultarEstado(Estado.EN_PROGRESO);
            DefaultTableModel modeloTabla=(DefaultTableModel)this.tbEnProgreso.getModel();
            modeloTabla.setRowCount(0);
            for (Tarea tarea : tareasEnProgreso) {
                Object[] filaDatos=new Object[2];
                filaDatos[0]=tarea.getNombre();
                filaDatos[1]=tarea.getDescripcion();
                modeloTabla.addRow(filaDatos);
            }
            if(!tareasEnProgreso.isEmpty()){
                habilitarBotonIniciar();
            }else{
                restablecer();
            }
        }catch(Exception ex){
              JOptionPane.showMessageDialog(this, "No se pudieron obtener los datos de la tabla"+" "+ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE); 
        }
    }
    
    private void cargarTareasTerminadas(){
        try{    
            this.tareasTerminadas=this.tareaDao.consultarEstado(Estado.TERMINADA);
            DefaultTableModel modeloTabla=(DefaultTableModel)this.tbTerminado.getModel();
            modeloTabla.setRowCount(0);
            for (Tarea tarea : tareasTerminadas) {
                Object[] filaDatos=new Object[2];
                filaDatos[0]=tarea.getNombre();
                filaDatos[1]=tarea.getDescripcion();
                modeloTabla.addRow(filaDatos);
            }
        }catch(Exception ex){
              JOptionPane.showMessageDialog(this, "No se pudieron obtener los datos de la tabla"+" "+ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE); 
        }
    }
    
    public boolean comprobarVacioTablaEnProgreso(){
        if(tareasEnProgreso.isEmpty()){
            return true;
        }
        return false;
    }
    
    public void habilitarBotonIniciar(){
        btnIniciarReanudar.setEnabled(true);
    }
    
    public void restablecer(){
        if(timer.isRunning())timer.stop();
        minutos=0;
        segundos=0;
        numDescansos=0;
        descanso=false;
        btnIniciarReanudar.setEnabled(false);
        btnPausar.setEnabled(false);
        btnCancelar.setEnabled(false);
    }
    
    private void empezarTemporizador(){
        if(minutos==0 && segundos==0){
            establecerTiempo();
        }
        timer.start();
    }
    
    private void establecerTiempo(){
        if(descanso){
            switch(numDescansos){
                case 3: 
                    minutos=10;
                    break;
                default: 
                    minutos= 3;
                    break;
            }
        }else{
            minutos=5;
        }
        actualizarTemporizador();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Salir;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnIniciarReanudar;
    private javax.swing.JButton btnPausar;
    private javax.swing.JLabel fondo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblInformacionDescansos;
    private javax.swing.JLabel lblNumDescansos;
    private javax.swing.JLabel lblTemporizador;
    private javax.swing.JTable tbEnProgreso;
    private javax.swing.JTable tbPendiente;
    private javax.swing.JTable tbTerminado;
    // End of variables declaration//GEN-END:variables

}
